#ifndef FACELANDMARK68_H
#define FACELANDMARK68_H

#define FACELANDMARK68                   0

#define FL68_JAWLINE_START_INDEX         0
#define FL68_JAWLINE_END_INDEX           16

#define FL68_LEFT_EYEBROW_START_INDEX    17
#define FL68_LEFT_EYEBROW_END_INDEX      21

#define FL68_RIGHT_EYEBROW_START_INDEX   22
#define FL68_RIGHT_EYEBROW_END_INDEX     26

#define FL68_NOSE_VERTICAL_START_INDEX   27
#define FL68_NOSE_VERTICAL_END_INDEX     30

#define FL68_NOSE_HORIZONTAL_START_INDEX 31
#define FL68_NOSE_HORIZONTAL_END_INDEX   35

#define FL68_LEFT_EYE_START_INDEX        36
#define FL68_LEFT_EYE_END_INDEX          41

#define FL68_RIGHT_EYE_START_INDEX       42
#define FL68_RIGHT_EYE_END_INDEX         47

#define FL68_MOUTH_START_INDEX           48
#define FL68_MOUTH_END_INDEX             67

#endif // FACELANDMARK68_H
